import { Dimensions } from 'react-native'
const { width, height } = Dimensions.get('window')
const Global = {
    black: 'rgba(34, 34, 34, 1)',
    white: 'rgba(255, 255, 255, 1)',
    blue: 'rgba(28, 93, 153, 1)',
    bluegreen: 'rgba(99, 159, 171, 1)',
    bluelight: 'rgba(187, 205, 229, 1)',
    bluelight2: '#cfe4fa',
    bluelight3: '#d9eafc',
    backgroundModal: 'rgba(34, 34, 34, 0.3)',
    textColor: 'rgba(34, 34, 34, 1)',
    red: 'rgba(255, 0, 0, 0.5)',
    redInputs: 'rgba(255, 1, 0, 0.04)',
    redCanceled: 'rgba(255, 0, 0, 0.1)',
    fontSize: '18px',
    fontSize_n: 18,
    fontSizeTitle: '30px',
    fontSizeTitle_n: 30,
    padding: '8px',
    padding_n: 8,
    margin: '5px',
    width: '8px',
    MaxWidth:'70px',
    borderRadius: '8px',
    borderRadius_n: 8,
    widthButtonHeader: '50px',
    marginInputs: '4px',
    marginInputs_n: 5,
    sizeIconHeader: 30,
    sizeIconSearch: 20,
    SizeIconSelectInput: 30,
    paddingHeightInputs: '4px',
    paddingHeightInputs_N: 4,
    backgroundInputs: '#FFF',
    MaxHeigtOptionsSelect: 180,
    colorIconHeader: 'rgba(255, 255, 255, 1)',
    colorIconSearch: 'rgba(34, 34, 34, 1)',
    ColorIconSelectInput: 'rgba(34, 34, 34, 1)',
    iconSave: 'save',
    iconBack: 'angle-left',
    iconSearchBox: 'search',
    IconSelectInputClose: 'angle-down',
    IconSelectInputOpen: 'angle-up',
    IconAdd: 'plus',
    IconNew: 'plus-square',
    IconSend:'list-ul',
    IconTrash: 'trash',
    IconCancel: 'ban',
    IconEdit: 'edit',
    IconSync: 'refresh',
    IconMenu: 'navicon',
    IconDefault:'trash',
    sizeiconAdd: 40,
    colorPlaceholder: 'rgba(34, 34, 34, 1)',
    MaxHeigtBoxItemColeta: '70',
    MaxHeigtBoxColeta: '80',
    colorObservation: 'rgba(99, 159, 171, 1)',
    width: width,
    colorButtonDelete: 'rgba(28, 93, 153, 1)',
}

export default Global