const GText = {
    title: 'Coletas',
    MyColetas: 'Minhas Coletas',
    SendedColetas: 'Coletas Enviadas',
    NewColeta: 'Nova Coleta',
    Config: 'Configurações',
    Send: 'Enviar',
    Cancel: 'Cancelar',
    SearchBox: 'Nome Cliente',




    nIdMobile: 'IdMobile',
    nCodImport: 'Cod_Importacao',
    nCodCompany: 'CodEmpresa',
    nCodBranch: 'CodFilial',
    nCodSalesman: 'CodVendedorIndex',
    nCodPriority: 'CodPrioridade',
    nColetaDate: 'DataColeta',
    nCodSalesman: 'CodVendedor',
    nCodCollector: 'CodColetador',
    nCodTechnician: 'CodTecnico',
    nCodClient: 'CodCliente',
    nCodSituation: 'CodSituacao',
    nCodProduct: 'CodProduto',
    nCodBrand: 'CodMarca',
    nCodType: 'CodTipo',
    nCodCancel: 'CodCancelamento',
    nItem: 'Item',
    nColetaNumber: 'NumeroColeta',
    nStatus: 'Status',
    nInclusionDate: 'DataLancamento',
    nInclusionHour: 'HoraLancamento',
    nInclusionUser: 'UsuarioLancamento',
    nInclusionStation: 'EstacaoLancamentos',
    nDate: 'DataEmissao',
    nNameClient: 'NomeCliente',
    nIdIdentityClient: 'CPF_CNPJ',
    nPhone: 'Celular',
    nWarranty: 'Garantia',
    nImportColeta: "ImportaColeta",
    nNameProduct: 'NomeProduto',
    nSerieNumber: 'NumeroSerie',
    nBrand: 'Marca',
    nModelo: 'Modelo',
    nDimension: 'Dimensao',
    nDesign: 'Desenho',
    nFireNumber: 'NumeroFogo',
    nDotNumber: 'NumeroDot',  
    nBoard: 'Placa',
    nServicesExec: 'ServicosExecutar',
    nInitialExam: 'ExameInicial',
    nObservation: 'Observacao',
    nValue: 'Valor',
    nCancelObseervation: 'ObservacaoCancelamento',
    nCancelDate: 'DataCancelamento',
    nCancelHour: 'HoraCancelamento',
    nCancelUser: 'UsuarioCancelamento',
    nCancelStation: 'EstacaoCancelamento',

    pIdMobile: 'IdMobile',
    pCodImport: 'Cod_Importacao',
    pCodCompany: 'CodEmpresa',
    pCodBranch: 'CodFilial',
    pCodSalesman: 'CodVendedorIndex',
    pCodPriority: 'CodPrioridade',
    pColetaDate: 'DataColeta',
    pCodSalesman: 'CodVendedor',
    pCodCollector: 'CodColetador',
    pCodTechnician: 'CodTecnico',
    pCodClient: 'CodCliente',
    pCodSituation: 'CodSituacao',
    pCodProduct: 'CodProduto',
    pCodBrand: 'CodMarca',
    pCodType: 'CodTipo',
    pCodCancel: 'CodCancelamento',
    pItem: 'Item',
    pColetaNumber: 'NumeroColeta',
    pStatus: 'Status',
    pInclusionDate: 'DataLancamento',
    pInclusionHour: 'HoraLancamento',
    pInclusionUser: 'UsuarioLancamento',
    pInclusionStation: 'EstacaoLancamentos',
    pDate: 'DataEmissao',
    pNameClient: 'Cliente',
    pIdIdentityClient: 'CPF_CNPJ',
    pPhone: 'Celular',
    pWarranty: 'Garantia',
    pImportColeta: "ImportaColeta",
    pNameProduct: 'NomeProduto',
    pSerieNumber: 'Série:',
    pBrand: 'Marca:',
    pModelo: 'Modelo',
    pDimension: 'Bitola:',
    pDesign: 'Desenho:',
    pFireNumber: 'NumeroFogo',
    pDotNumber: 'NumeroDot',  
    pBoard: 'Placa:',
    pServicesExec: 'Serviços a executar',
    pInitialExam: 'ExameInicial',
    pObservation: 'Observação:',
    pValue: '00,00',
    pCancelObseervation: 'ObservacaoCancelamento',
    pCancelDate: 'DataCancelamento',
    pCancelHour: 'HoraCancelamento',
    pCancelUser: 'UsuarioCancelamento',
    pCancelStation: 'EstacaoCancelamento',

}

export default GText